### ISSUE TITLE
Cannot declare class Qbhy\LaravelApiAuth\Middleware\Middleware, because the name is already in use

### ISSUE THREAD

**Issue by moore0903** [96qbhy/laravel-api-auth#2]
Cannot declare class Qbhy\LaravelApiAuth\Middleware\Middleware, because the name is already in use
不知道我哪里出错了

**Comment by moore0903** [comment]
Kernel.php 里面的 $routeMiddleware
应该是'api_auth' => \Qbhy\LaravelApiAuth\Middleware\Middleware::class,

**Comment by qbhy** [comment]
这确实是个bug，中间件命名空间写错了。感谢你的反馈。

**Comment by qbhy** [comment]
目前已经修复，最新版本 4.0.1。
@moore0903
