### ISSUE TITLE
laravel 5.6 安装包错误

### ISSUE THREAD

**Issue by guiyatao** [96qbhy/laravel-api-auth#3]
:\php\laravel\laravel
λ composer require 96qbhy/laravel-api-auth
Using version ^4.0 for 96qbhy/laravel-api-auth
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In ProviderRepository.php line 208:

  Class 'Modules\Blog\Providers\BlogServiceProvider' not found

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by guiyatao** [comment]
5.5没问题

**Comment by qbhy** [comment]
![image](https://user-images.githubusercontent.com/24204533/39290824-7d2ea32e-4963-11e8-901d-b58511d5ecb5.png)
应该是你5.6的项目应用了一个不存在的服务提供者导致的，并不是 api-auth 包的问题哦。

**Comment by guiyatao** [comment]
![image](https://user-images.githubusercontent.com/12374577/39303585-4c5b9902-4989-11e8-9119-02a56e9c352a.png)
这个命名空间错了导致安装不上

**Comment by qbhy** [comment]
这个问题已经修复了，谢谢反馈。
@guiyatao
